apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "reverseproxy"
    port: 8080
    targetPort: 8080
  selector:
    app: reverseproxy